// COLLECTION : SET OF DIFFERENT OBJECS,ON THESE OBJECTS WE CAN PERFORM DIFF OPERATIONS (Daigram 40:42) ; ITERATOR USED ON COLLECTION
// REAL TIME EXAMPLE OF COLLECTION : OVERSEAS AND DIFF STATE PLAYERS IN ONE TEAM OF IPL
// REAL TIME EXAMPLE OF ARRAY : ALL PLAYERS OF ONE STATE IN ONE TEAM IN RANAJI TROPHY
// DEMO : ARRAYLIST()
// JAVA EXAM : OCPJP ; OCAJiP
